from enum import Enum
from drf_yasg.openapi import TYPE_FILE, TYPE_ARRAY, TYPE_OBJECT, TYPE_NUMBER, TYPE_BOOLEAN, TYPE_INTEGER, TYPE_STRING


class APIParamDataType(Enum):
    FILE = TYPE_FILE
    ARRAY = TYPE_ARRAY
    OBJECT = TYPE_OBJECT
    FLOAT = TYPE_NUMBER
    BOOLEAN = TYPE_BOOLEAN
    INTEGER = TYPE_INTEGER
    STRING = TYPE_STRING
